name: Daily Job - Daily Game Wiki Scraper

on:
  push: 
    branches:
      - main
      - master
  # schedule:
  #   - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  scrape_and_process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install wikiextractor
      run: pip install wikiextractor

    - name: Clone ScrapeFandom repository
      run: git clone https://github.com/AYESDIE/ScrapeFandom.git

    - name: Install ScrapeFandom requirements
      run: pip install -r ScrapeFandom/requirements.txt

    - name: Install main requirements
      run: pip install -r requirements.txt

    - name: Run scraper script
      run: python main.py

    - name: Upload output artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wikis-output
        path: wikis.zip
